-- Insight Suggestions Table
-- Stores proactive learning suggestions generated by the insight engine.
-- Suggestions are generated after resource ingestion, periodically from activity,
-- or from gap detection analysis.

CREATE TABLE insight_suggestions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('mastery_catalyst', 'consolidation', 'gap_detection', 'debate_topic')),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  action_type TEXT NOT NULL CHECK (action_type IN ('evaluate', 'explore', 'freeform', 'debate', 'review')),
  action_data JSONB DEFAULT '{}',
  concept_ids TEXT[] DEFAULT '{}',
  priority REAL DEFAULT 0.5,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'dismissed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ
);

-- RLS
ALTER TABLE insight_suggestions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users see own suggestions"
  ON insight_suggestions FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "Users insert own suggestions"
  ON insight_suggestions FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users update own suggestions"
  ON insight_suggestions FOR UPDATE USING (user_id = auth.uid());

-- Indexes
CREATE INDEX idx_insight_suggestions_user_status
  ON insight_suggestions(user_id, status, created_at DESC);
CREATE INDEX idx_insight_suggestions_user_type
  ON insight_suggestions(user_id, type);
